# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.5.0-dev20201110'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [12]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 449us/step - loss: 0.6299 - accuracy: 0.6306
Epoch 2/100
250/250 [==============================] - 0s 434us/step - loss: 0.4728 - accuracy: 0.8003
Epoch 3/100
250/250 [==============================] - 0s 434us/step - loss: 0.4446 - accuracy: 0.8072
Epoch 4/100
250/250 [==============================] - 0s 438us/step - loss: 0.4269 - accuracy: 0.8199
Epoch 5/100
250/250 [==============================] - 0s 426us/step - loss: 0.4234 - accuracy: 0.8133
Epoch 6/100
250/250 [==============================] - 0s 432us/step - loss: 0.4151 - accuracy: 0.8217
Epoch 7/100
250/250 [==============================] - 0s 428us/step - loss: 0.4138 - accuracy: 0.8191
Epoch 8/100
250/250 [==============================] - 0s 425us/step - loss: 0.4008 - accuracy: 0.8310
Epoch 9/100
250/250 [==============================] - 0s 430us/step - loss: 0.3980 - accuracy: 0.8309
Epoch 10/100
250/250 [==============================] - 0s 421us/step - l

250/250 [==============================] - 0s 422us/step - loss: 0.3326 - accuracy: 0.8677
Epoch 80/100
250/250 [==============================] - 0s 422us/step - loss: 0.3268 - accuracy: 0.8704
Epoch 81/100
250/250 [==============================] - 0s 420us/step - loss: 0.3368 - accuracy: 0.8608
Epoch 82/100
250/250 [==============================] - 0s 423us/step - loss: 0.3288 - accuracy: 0.8668
Epoch 83/100
250/250 [==============================] - 0s 445us/step - loss: 0.3307 - accuracy: 0.8664
Epoch 84/100
250/250 [==============================] - 0s 422us/step - loss: 0.3283 - accuracy: 0.8692
Epoch 85/100
250/250 [==============================] - 0s 416us/step - loss: 0.3302 - accuracy: 0.8667
Epoch 86/100
250/250 [==============================] - 0s 415us/step - loss: 0.3329 - accuracy: 0.8670
Epoch 87/100
250/250 [==============================] - 0s 416us/step - loss: 0.3221 - accuracy: 0.8683
Epoch 88/100
250/250 [==============================] - 0s 417us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [40]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [42]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(accuracy_score(y_test,y_pred))
print(cm)

0.8615
[[1531   64]
 [ 213  192]]


In [33]:
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression(C=0.01).fit(X_train,y_train)
LR_model

LogisticRegression(C=0.01)

In [34]:
yhat = LR_model.predict(X_test)

In [35]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[1543   52]
 [ 327   78]]
              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1595
           1       0.60      0.19      0.29       405

    accuracy                           0.81      2000
   macro avg       0.71      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

0.8105


In [36]:
from sklearn.tree import DecisionTreeClassifier
DT_model = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
DT_model.fit(X_train,y_train)
DT_model

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [38]:
yhat = DT_model.predict(X_test)
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[1519   76]
 [ 214  191]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1595
           1       0.72      0.47      0.57       405

    accuracy                           0.85      2000
   macro avg       0.80      0.71      0.74      2000
weighted avg       0.84      0.85      0.84      2000

0.855


In [43]:
from numpy import loadtxt
from xgboost import XGBClassifier

In [46]:
model = XGBClassifier()
model.fit(X_train, y_train)
yhat = model.predict(X_test)

In [45]:
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score
def metrics(true, preds): 
    """
    Function to calculate evaluation metrics
    parameters: true values, predictions
    prints accuracy, recall, precision and f1 scores
    """
    accuracy = accuracy_score(true, preds)
    recall = recall_score(true, preds, average = 'weighted')
    precision = precision_score(true, preds, average = 'weighted')
    f1score = f1_score(true, preds, average = 'weighted')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))

In [47]:
metrics(y_test,yhat)

accuracy: 0.853, recall: 0.853, precision: 0.8430310764192854, f1-score: 0.845074120396949
