In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gc
import os
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

# might be needed depending on your version of Jupyter
%matplotlib inline

In [51]:
df = pd.read_csv('house_price_clean_data.csv')

In [52]:
df = df.sample(frac=0.05,random_state=101)

In [53]:
df

Unnamed: 0  loan_amnt  term  int_rate  installment  annual_inc    dti  \
204474      204901    14800.0    36     18.49       538.71    104540.0  13.12   
226393      226870    31000.0    60     17.57       779.97    122000.0  27.46   
241222      241733    22000.0    60      7.89       444.93     71400.0  21.29   
225006      225481    20000.0    36     10.78       652.70    100000.0  17.86   
104454      104657    18625.0    60     17.57       468.61     41500.0  18.80   
...            ...        ...   ...       ...          ...         ...    ...   
75902        76044     7725.0    36     11.99       256.55    105000.0   9.38   
363237      363988     6000.0    36     20.49       224.49     35000.0  17.25   
287858      288456    10000.0    36     13.35       338.63     70000.0  22.17   
311763      312415     3000.0    36      7.39        93.17     13500.0   5.88   
80792        80936     6500.0    60     15.57       156.59     93024.0  24.48   

        open_acc  pub_rec  revol_bal  ...  05113  11650  22690  29597  30723  \
204474      10.0      0.0    21241.0  ...      1      0      0      0      0   
226393      20.0      0.0    36941.0  ...      0      0      0      1      0   
241222       9.0      0.0     5212.0  ...      0      0      0      0      0   
225006      14.0      0.0    11139.0  ...      0      0      1      0      0   
104454      20.0      0.0    27975.0  ...      0      0      0      1      0   
...          ...      ...        ...  ...    ...    ...    ...    ...    ...   
75902        9.0      0.0     1070.0  ...      0      0      0      1      0   
363237       8.0      1.0     5302.0  ...      0      0      0      0      1   
287858      15.0      0.0    14700.0  ...      0      0      0      0      0   
311763       7.0      1.0     3688.0  ...      0      0      0      0      0   
80792       14.0      0.0    17458.0  ...      0      0      1      0      0   

        48052  70466  86630  93700  earliest_cr_year  
204474      0      0      0      0              1992  
226393      0      0      0      0              1996  
241222      0      0      0      0              2003  
225006      0      0      0      0              1994  
104454      0      0      0      0              1993  
...       ...    ...    ...    ...               ...  
75902       0      0      0      0              1990  
363237      0      0      0      0              2000  
287858      0      0      0      1              1997  
311763      0      0      0      0              2001  
80792       0      0      0      0              1992  

[19761 rows x 80 columns]

In [54]:
from sklearn.model_selection import train_test_split
X = df.drop('loan_repaid',axis=1).values
y = df['loan_repaid'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=101)

In [55]:
from sklearn.preprocessing import MinMaxScaler

In [56]:
scaler = MinMaxScaler()

In [57]:
scaler.fit(X_train)

MinMaxScaler()

In [58]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Logistic Regression

In [59]:
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression(C=0.01).fit(X_train,y_train)
LR_model

LogisticRegression(C=0.01)

In [60]:
yhat = LR_model.predict(X_test)

In [61]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[ 271  509]
 [   0 3173]]
              precision    recall  f1-score   support

           0       1.00      0.35      0.52       780
           1       0.86      1.00      0.93      3173

    accuracy                           0.87      3953
   macro avg       0.93      0.67      0.72      3953
weighted avg       0.89      0.87      0.84      3953

0.8712370351631672


# K Nearest Neighbor(KNN)

In [62]:
%%time
from sklearn.neighbors import KNeighborsClassifier
k = 3
#Train Model and Predict  
kNN_model = KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
kNN_model
yhat = kNN_model.predict(X_test)
yhat[0:5]

Wall time: 7.09 s


array([1, 1, 1, 1, 1], dtype=int64)

In [ ]:
%%time
Ks=10
mean_acc=np.zeros((Ks-1))
std_acc=np.zeros((Ks-1))
ConfustionMx=[];
for n in range(1,Ks):
    
    #Train Model and Predict  
    kNN_model = KNeighborsClassifier(n_neighbors=n).fit(X_train,y_train)
    yhat = kNN_model.predict(X_test)
    
    
    mean_acc[n-1]=np.mean(yhat==y_test);
    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])
mean_acc

In [63]:
from sklearn.neighbors import KNeighborsClassifier
k = 7
#Train Model and Predict  
kNN_model = KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
kNN_model

KNeighborsClassifier(n_neighbors=7)

In [64]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[ 302  478]
 [ 180 2993]]
              precision    recall  f1-score   support

           0       0.63      0.39      0.48       780
           1       0.86      0.94      0.90      3173

    accuracy                           0.83      3953
   macro avg       0.74      0.67      0.69      3953
weighted avg       0.82      0.83      0.82      3953

0.833544143688338


# Decision Tree

In [107]:
%%time
from sklearn.tree import DecisionTreeClassifier
DT_model = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
DT_model.fit(X_train,y_train)
DT_model

Wall time: 86.3 ms


DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [108]:
yhat = DT_model.predict(X_test)

In [109]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[ 329  451]
 [   0 3173]]
              precision    recall  f1-score   support

           0       1.00      0.42      0.59       780
           1       0.88      1.00      0.93      3173

    accuracy                           0.89      3953
   macro avg       0.94      0.71      0.76      3953
weighted avg       0.90      0.89      0.87      3953

0.88590943587149


In [110]:
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score
def metrics(true, preds): 
    """
    Function to calculate evaluation metrics
    parameters: true values, predictions
    prints accuracy, recall, precision and f1 scores
    """
    accuracy = accuracy_score(true, preds)
    recall = recall_score(true, preds, average = 'weighted')
    precision = precision_score(true, preds, average = 'weighted')
    f1score = f1_score(true, preds, average = 'weighted')
    print ('accuracy: {}, recall: {}, precision: {}, f1-score: {}'.format(accuracy, recall, precision, f1score))

In [111]:
metrics(y_test,yhat)

accuracy: 0.88590943587149, recall: 0.88590943587149, precision: 0.9001077925000656, f1-score: 0.8664957925882921


# Support Vector Machine

In [68]:
%%time
from sklearn import svm
SVM_model = svm.SVC()
SVM_model.fit(X_train, y_train) 

Wall time: 11 s


SVC()

In [69]:
yhat = SVM_model.predict(X_test)

In [70]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']}

In [71]:
from sklearn.model_selection import GridSearchCV

In [72]:
grid = GridSearchCV(svm.SVC(),param_grid,refit=True,verbose=3)

In [73]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.802, total=  24.5s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   24.4s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.802, total=  25.6s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   50.0s remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.802, total=  25.8s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.802, total=  28.6s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.802, total=  29.6s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.888, total=  10.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.887, total=  10.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.887, total=  10.4s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.888, total=  10.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] .

[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.888, total=  11.2s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.887, total=  10.8s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.887, total=  11.1s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.888, total=  10.9s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.887, total=  11.3s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.888, total=  10.6s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.887, total=  10.2s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] .

[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.888, total=  20.1s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] ..... C=1000, gamma=0.001, kernel=rbf, score=0.887, total=  23.4s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.888, total=  12.1s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.887, total=  10.9s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.887, total=  12.1s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.888, total=  12.2s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.887, total=  11.8s


[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed: 33.0min finished


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [74]:
grid.best_params_

{'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}

In [112]:
grid_predictions = grid.predict(X_test)

In [113]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[ 329  451]
 [   0 3173]]
              precision    recall  f1-score   support

           0       1.00      0.42      0.59       780
           1       0.88      1.00      0.93      3173

    accuracy                           0.89      3953
   macro avg       0.94      0.71      0.76      3953
weighted avg       0.90      0.89      0.87      3953

0.88590943587149


In [114]:
metrics(y_test,yhat)

accuracy: 0.88590943587149, recall: 0.88590943587149, precision: 0.9001077925000656, f1-score: 0.8664957925882921


# Random Forest

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
%%time
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1000, num = 5)]
max_depth = [int(x) for x in np.linspace(50, 300, num = 5)]
max_depth.append(None)
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth
              }

Wall time: 0 ns


In [ ]:
%%time
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, 
                               cv = 5, verbose=2, random_state=42, n_jobs = -1)
rf_random.fit(X_train, y_train)

F:\Anaconda\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 30 is smaller than n_iter=100. Running 30 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 5 folds for each of 30 candidates, totalling 150 fits


In [ ]:
rf_random.best_params_

In [115]:
clf = RandomForestClassifier(n_estimators= 100, max_depth = 50)
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=50)

In [116]:
yhat = clf.predict(X_test)

In [117]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[ 345  435]
 [   7 3166]]
              precision    recall  f1-score   support

           0       0.98      0.44      0.61       780
           1       0.88      1.00      0.93      3173

    accuracy                           0.89      3953
   macro avg       0.93      0.72      0.77      3953
weighted avg       0.90      0.89      0.87      3953

0.8881861877055401


In [118]:
metrics(y_test,yhat)

accuracy: 0.8881861877055401, recall: 0.8881861877055401, precision: 0.899112304902337, f1-score: 0.8705805933577658


In [119]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation,Dropout
from tensorflow.keras.constraints import max_norm

In [120]:
model = Sequential()

# https://stats.stackexchange.com/questions/181/how-to-choose-the-number-of-hidden-layers-and-nodes-in-a-feedforward-neural-netw


# input layer
model.add(Dense(78,  activation='relu'))
model.add(Dropout(0.5))

# hidden layer
model.add(Dense(39, activation='relu'))
model.add(Dropout(0.5))

# hidden layer
model.add(Dense(19, activation='relu'))
model.add(Dropout(0.5))

# output layer
model.add(Dense(units=1,activation='sigmoid'))

# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam')

In [127]:
model.fit(x=X_train, 
          y=y_train, 
          epochs=25,
          batch_size=256,
          validation_data=(X_test, y_test), 
          )

Epoch 1/25
62/62 [==============================] - 0s 3ms/step - loss: 0.2014 - val_loss: 0.4426
Epoch 2/25
62/62 [==============================] - 0s 2ms/step - loss: 0.2024 - val_loss: 0.4577
Epoch 3/25
62/62 [==============================] - 0s 2ms/step - loss: 0.2053 - val_loss: 0.4481
Epoch 4/25
62/62 [==============================] - 0s 2ms/step - loss: 0.1999 - val_loss: 0.4491
Epoch 5/25
62/62 [==============================] - 0s 2ms/step - loss: 0.1965 - val_loss: 0.4606
Epoch 6/25
62/62 [==============================] - 0s 2ms/step - loss: 0.2023 - val_loss: 0.4426
Epoch 7/25
62/62 [==============================] - 0s 2ms/step - loss: 0.1975 - val_loss: 0.4579
Epoch 8/25
62/62 [==============================] - 0s 2ms/step - loss: 0.1996 - val_loss: 0.4702
Epoch 9/25
62/62 [==============================] - 0s 2ms/step - loss: 0.1982 - val_loss: 0.4604
Epoch 10/25
62/62 [==============================] - 0s 2ms/step - loss: 0.1986 - val_loss: 0.4682
Epoch 11/25
62/62 [

In [128]:
yhat = model.predict_classes(X_test)

In [129]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[ 391  389]
 [  77 3096]]
              precision    recall  f1-score   support

           0       0.84      0.50      0.63       780
           1       0.89      0.98      0.93      3173

    accuracy                           0.88      3953
   macro avg       0.86      0.74      0.78      3953
weighted avg       0.88      0.88      0.87      3953

0.8821148494814065


In [130]:
metrics(y_test,yhat)

accuracy: 0.8821148494814065, recall: 0.8821148494814065, precision: 0.8779389050419426, f1-score: 0.8701413089229507


In [131]:
from numpy import loadtxt
from xgboost import XGBClassifier

In [132]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [133]:
yhat = model.predict(X_test)

In [134]:
print(confusion_matrix(y_test,yhat))
print(classification_report(y_test,yhat))
print(accuracy_score(y_test,yhat))

[[ 384  396]
 [  74 3099]]
              precision    recall  f1-score   support

           0       0.84      0.49      0.62       780
           1       0.89      0.98      0.93      3173

    accuracy                           0.88      3953
   macro avg       0.86      0.73      0.77      3953
weighted avg       0.88      0.88      0.87      3953

0.8811029597773843


In [135]:
metrics(y_test,yhat)

accuracy: 0.8811029597773843, recall: 0.8811029597773843, precision: 0.8771712419171037, f1-score: 0.8685113715352001


In [102]:
model= XGBClassifier(learning_rate=0.02, n_estimators=600, objective='binary:logistic',nthread=1)
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.02, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=600, n_jobs=1, nthread=1, num_parallel_tree=1,
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [105]:
params = {
        'min_child_weight': [1, 5, 10],
        'gamma': [0.5, 1, 1.5, 2, 5],
        'subsample': [0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3, 4, 5]
        }

In [ ]:
folds = 3
param_comb = 5

skf = StratifiedKFold(n_splits=folds, shuffle = True, random_state = 1001)

random_search = RandomizedSearchCV(xgb, param_distributions=params, n_iter=param_comb, scoring='roc_auc', n_jobs=4, cv=skf.split(X,Y), verbose=3, random_state=1001 )

# Here we go
start_time = timer(None) # timing starts from this point for "start_time" variable
random_search.fit(X, Y)
timer(start_time) # timing ends here for "start_time" variable